# Generated by Django 4.1.4 on 2023-06-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-doctor.jpg', null=True, upload_to=''),
        ),
    ]
