# Generated by Django 4.1.4 on 2023-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='service',
            field=models.ManyToManyField(to='hcam.service'),
        ),
    ]
