# Generated by Django 4.1.4 on 2023-04-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcam', '0003_hospital_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Hospital_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
