# Generated by Django 4.1.4 on 2023-04-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcam', '0004_alter_hospital_hospital_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='Hospital_image',
            new_name='hospital_image',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_disc',
        ),
        migrations.AddField(
            model_name='hospital',
            name='more_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
